language: elixir
elixir: 1.9
notifications:
  recipients:
    - bruce.williams@cargosense.com
    - ben.wilson@cargosense.com
otp_release:
  - 22.0
script: "MIX_ENV=test mix local.hex --force && MIX_ENV=test mix do deps.get, test"
